backend:
  name: github
  repo: juandacu/CarbonSense
  branch: main
  base_url: https://carbonsense-oauth.onrender.com
  auth_endpoint: auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "data/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "thumbnail", label: "Thumbnail", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
