backend:
  name: github
  repo: juandacu/CarbonSense          # your main content repo
  branch: main
  base_url: https://carbonsense-oauth.onrender.com
  auth_endpoint: /auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "data/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
